spring.datasource.url=jdbc:postgresql://localhost:5432/Radius
spring.datasource.username=postgres
spring.datasource.password=Eddie3030$
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false