spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.config.import=optional:secrets.properties
foursquare.apiKey=${FOURSQUARE_API_KEY}

server.port=${PORT:8080}
textbelt.api.key=${TEXTBELT_API_KEY}