// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMuqN2_3E8Mn7UtdtnOd_pJC46binNwEY',
    appId: '1:397577239288:web:8622a97fa8a2dac162590d',
    messagingSenderId: '397577239288',
    projectId: 'radius-6ad92',
    authDomain: 'radius-6ad92.firebaseapp.com',
    storageBucket: 'radius-6ad92.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkEwQDKC03CQe6OR8xLmA-g3hwkmOiF2E',
    appId: '1:397577239288:android:470f51efebc5f75562590d',
    messagingSenderId: '397577239288',
    projectId: 'radius-6ad92',
    storageBucket: 'radius-6ad92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsNF6YtaIj3U5Ocr1sy8e_hwRYll8x5S8',
    appId: '1:397577239288:ios:28ddc306afe32a8162590d',
    messagingSenderId: '397577239288',
    projectId: 'radius-6ad92',
    storageBucket: 'radius-6ad92.firebasestorage.app',
    iosBundleId: 'com.eddie.radiusFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsNF6YtaIj3U5Ocr1sy8e_hwRYll8x5S8',
    appId: '1:397577239288:ios:283d744782f967e962590d',
    messagingSenderId: '397577239288',
    projectId: 'radius-6ad92',
    storageBucket: 'radius-6ad92.firebasestorage.app',
    iosBundleId: 'com.example.radiusFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMuqN2_3E8Mn7UtdtnOd_pJC46binNwEY',
    appId: '1:397577239288:web:16645e73f1d431cc62590d',
    messagingSenderId: '397577239288',
    projectId: 'radius-6ad92',
    authDomain: 'radius-6ad92.firebaseapp.com',
    storageBucket: 'radius-6ad92.firebasestorage.app',
  );
}
